### PR TITLE
Allow selecting the menu button's text

### PR DESCRIPTION
**Pull request by shepmaster**
You still have to start the drag from off of the button, but it's
better.

### CODE REVIEW

**Comment by shepmaster** [comment]
/cc @RalfJung 

selecty

**Comment by RalfJung** [comment]
Cool :)
In Firefox you can alt-click to start selecting text inside a link, but at least without that PR even that does not work the playground.

**Comment by shepmaster** [comment]
> to start selecting text inside a link

These are `<button>` elements, and if you start and end the click inside them, it counts as clicking the button, which closes the menu. If you are on Linux, it might trigger the alternate/middle mouse button clipboard, but on e.g. stock macOS you have to start or end the drag off the button. 😉

**Comment by RalfJung** [comment]
Confirmed that this also works in Firefox. :D

**Pull request merged**
