### PR TITLE
Update to Node v14.15.1

### PR DESCRIPTION
**Pull request by camelid**
This is the latest LTS version.

### CODE REVIEW

**Comment by camelid** [comment]
Even if we don't upgrade all the way to v15, it might make sense to upgrade to v14 (the LTS).

**Comment by shepmaster** [comment]
> it might make sense to upgrade to v14

This is what I'd prefer, yeah. [Even numbered versions](https://nodesource.com/blog/understanding-how-node-js-release-lines-work/) become LTS versions. Since I don't care to know all the intricacies of Node versioning, I've been trying to stay with those. 😉 

> This is the latest version that Homebrew installs for me

Ditto. What I do is:

```
% brew install node@14
```

Then I have a shell alias:

```zsh
alias node14='source ~/bin/node14'
```

That calls the script:

```zsh
PATH="/usr/local/opt/node@14/bin:$PATH"
```

This is pretty janky, and there are real solutions like [nvm](https://github.com/nvm-sh/nvm), but it's just the right amount of simple for me.

**Comment by camelid** [comment]
> Since I don't care to know all the intricacies of Node versioning, I've been trying to stay with those. 😉

That sounds good to me! Yeah, their versioning scheme is not very approachable :)

**Comment by camelid** [comment]
Your solution works like a charm, thank you :)

**Review by shepmaster — APPROVED** [review]

**Comment by shepmaster** [comment]
Thanks!

**Pull request merged**
