### PR TITLE
Make PLAYGROUND_GITHUB_TOKEN optional

### PR DESCRIPTION
**Pull request by dtolnay**
I am working on a PR for something totally unrelated to gists, and didn't want to bother setting up a GitHub token just so that the server wouldn't crash on startup.

### CODE REVIEW

**Comment by dtolnay** [comment]
I guess. Really I'd like for `cargo run` to work without any `.env` file. Setting up `.env` is an extra step in the dev workflow for unclear benefit (to me). Would you be open to a PR that infers `PLAYGROUND_UI_ROOT=$CARGO_MANIFEST_DIR/frontend/build` by default?

I can also add logging at server startup so that people can't get tripped up by the new defaults:

- `warn!` if PLAYGROUND_GITHUB_TOKEN is absent, calling out that gist won't work
- `info!` giving the absolute path to inferred PLAYGROUND_UI_ROOT
- `error!` if `PLAYGROUND_UI_ROOT/index.html` does not exist

**Comment by dtolnay** [comment]
Screenshot from 2022-06-28 22-03-11

**Comment by shepmaster** [comment]
This makes sense to me. What I want to avoid is starting the server (appearing to work) but then later on discovering that something is broken. This applies both for contributors as well as when deploying to production — a big bang error at the beginning is much easier to notice.

I tried to make a change to your first commit, but perhaps you did not enable changes to the pull request from maintainers. Please amend it with

```diff
diff --git a/ui/src/main.rs b/ui/src/main.rs
index 0073589..7ebd7a6 100644
--- a/ui/src/main.rs
+++ b/ui/src/main.rs
@@ -2,7 +2,7 @@
 
 use crate::env::PLAYGROUND_GITHUB_TOKEN;
 use serde::{Deserialize, Serialize};
-use snafu::Snafu;
+use snafu::prelude::*;
 use std::{
     convert::TryFrom,
     net::SocketAddr,
@@ -109,10 +109,10 @@ impl GhToken {
     }
 
     fn must_get(&self) -> Result<String> {
-        match &self.0 {
-            Some(token) => Ok(String::clone(token)),
-            None => Err(Error::NoGithubToken),
-        }
+        self.0
+            .as_ref()
+            .map(|s| String::clone(s))
+            .context(NoGithubTokenSnafu)
     }
 }
 
```

> Would you be open to a PR that infers `PLAYGROUND_UI_ROOT=$CARGO_MANIFEST_DIR/frontend/build` by default?
> * `error!` if `PLAYGROUND_UI_ROOT/index.html` does not exist

Yeah, that is probably better than the current state.

**Comment by dtolnay** [comment]
Amended. _"perhaps you did not enable changes to the pull request from maintainers"_ &mdash; I know the checkbox you are talking about but I don't see it on this PR. :crying_cat_face: Maybe because I am using an org fork and not a personal fork. I invited you as a collaborator on my fork so that you'll be able to push to any future PRs.

**Review by shepmaster — APPROVED** [review]

**Pull request merged**
